services:
  app:
    build:
      context: .
    container_name: node_app
    ports:
      - "3000:3000"  
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Motdepasse
      - DB_NAME=todolist
      - DATABASE_URL=postgresql://postgres:Motdepasse@db:5432/todolist?schema=public
      - PORT=3000

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Motdepasse
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data: